cek sifat random
Kokoronationz/mirai pull request #2
Opened 2021-11-09 22:01 UTC by Jauhariq

2021-11-10 00:43 UTC, Kokoronationz commented
Jangan NSFW lah...

2021-11-10 00:44 UTC, Jauhariq commented
> Jangan NSFW lah...

Ga ada nsfw

2021-11-10 00:55 UTC, unx21 commented
> Jangan NSFW lah...

zettairyouiki random img, bukan nsfw, tapi gatau juga cuma kadang muncul wkwkwkk

2021-11-12 02:41 UTC, Kokoronationz approved these changes

2021-11-12 02:42 UTC, Kokoronationz requested changes
Coba pake Button Jo

2021-12-13 12:07 UTC, closed without merging